server:
  port: 8080
#  port=0 - random port
#  servlet:
#    context-path: /homepath

#debug: true

spring:
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    prefix: file:src/main/resources/templates/

  datasource:
    url: jdbc:h2:file:./data/myDB
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
