server:
  port: 8080
#  port=0 - random port
#  servlet:
#    context-path: /homepath

#debug: true

spring:
  thymeleaf:
    cache: false
#    prefix: classpath:/templates/
#    prefix: file:src/main/resources/templates/

  datasource:
    url: jdbc:h2:file:./data/assetportfolio;AUTO_SERVER=true
    driverClassName: org.h2.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
#    defer-datasource-initialization: true
    hibernate:
      ddl-auto: validate
#      ddl-auto: create
  h2:
    console:
      enabled: true
